### ISSUE TITLE
PSA Storage test 406 Flags not supported test not cognisant of flags behaviour

### ISSUE THREAD

**Issue by simonqhughes** [ARM-software/psa-arch-tests#125]
The test is incorrect in that it sets a flag bit when an object
is created, and expects the bit always to be set in the flags retrieved by
psa_xx_get_info(). The specification defines this is not always the case.

The following outlines psuedo-code for this test:

```
 set create_flags = 0x800000000
  while (create_flags != 0)
    {
      psa_ps_set()
      psa_ps_get()
      // check xxx
      psa_ps_get_info()
      // check flag retrieved is the same at the value used to set
      psa_ps_remove()
      create_flags >>= 1
    }
```
```
However:
- This test doesn't respect the behaviour of defined flags:
       - PSA_STORAGE_FLAG_WRITE_ONCE
           - If this bit is set then the object cannot be deleted.
             psa_xx_remove() will fail but the test current checks the
            object can successfully be removed.
       - PSA_STORAGE_FLAG_NO_CONFIDENTIALITY
           - The psa_trusted_storage_linux implementation always stores
             files with authentication (because files are stored with
             ecryptfs). Therefore if _NO_CONFIDENTIALITY is requested then
             its accepted but files are still stored confidentially. This
             is allowed by the spec. The spec also says that if this
             happens the the _NO_CONFIDENTIALITY flag should not be
             reported with get_info().
  - Only 3 of the flag bits are defined. The specification should be
    modified to say either 1) the undefined flag bits
    are reserved and the operation of the flags is undefined, or 2)
    if flag bit is set then the value should be retained with the object
    i.e. the behaviour being tested for here, or 3) something else
    which specifies behaviour.
```

The following link shows a commit in a forked repo containing a work around:

https://github.com/ARM-software/psa-arch-tests/commit/acad60c96976aff5a201db2aec6b2c1033234506

**Comment by kotegowder** [comment]
Thank you for reporting the issue.

The latest code (in align with 1.0.0) from test_s006.c do not create the storage against PSA_STORAGE_FLAG_WRITE_ONCE that means we are not attempting for psa_its_remove. 

PSA_STORAGE_FLAG_NO_CONFIDENTIALITY has to be handled against the below line from spec:

"When reporting meta data, psa_ps_get_info() should report the actual protection level applied and not the requested level." (which is applicable to psa_its_get_info() as well)

So as you explained with your implementation psa_its_get_info() will not have bit set when psa_its_set() is requested with PSA_STORAGE_FLAG_NO_CONFIDENTIALITY flag. 

Since the implementation creating storage with higher security level - this has to be accepted. 

We will make changes for this.

**Comment by kotegowder** [comment]
This is addressed as part of github patchset.
