### ISSUE TITLE
Are psa/client.h and psa/service.h headers missing to run PSA FF?

### ISSUE THREAD

**Issue by zaya-mc** [ARM-software/psa-arch-tests#22]
We are trying to run the PSA FF on TrustedFirmware and PSA FF setup.sh looks for psa/client.h psa/services.h but we could find these headers neither in PSA FF nor TF-m. 

Just under the TF-m/interface/include directory, there are headers named psa_client.h and psa_services.h, are these headers required headers?

**Comment by jaypit02** [comment]
As per PSA FF 1.0-Beta-0 specification, PSA FF implementer must provide following header files to application and Secure Partition:

Header file name | API | Note
-- | -- | --
<psa/client.h> | Client API | Accessible to all applications.
<psa/service.h> | Secure Partition API | Only accessible to Secure Partition.

Due to this reason, PSA FF Test Suite doesn't contain them and it expects PSA FF implementer to provide these header files to it.  These header files can be provided to test Suite by providing header file include PATHs to setup.sh script. In your case, TF-M must provide these files to PSA FF Test Suite.

Since test suite contains the secure partition, the script also expects output files of secure partition manifests JSON to be provided as described below:

Header file name | API | Note
-- | -- | --
<psa_manifest/sid.h> | RoT Service IDs | Macro definitions derived from manifest files that map from RoT Service names to Service IDs (SIDs).
<psa_manifest/manifestfilename.h> | Manifest definitions | A set of source header files, one for each Secure Partition, containing internal definitions for the Secure Partition implementation. Each file name is based on the name of the Secure Partition’s manifest file. The name must not collide with other header files.

Where,  psa_manifest/manifestfilename.h for test suite should be psa_manifest/driver_partition_psa.h, 
psa_manifest/client_partition_psa.h and psa_manifest/server_partition_psa.h

**Comment by zaya-mc** [comment]
Thank you @jaypit02, in our case, it seems TF-m needs to be aligned with the PSA FF Beta specification. I will let TF-m team know.

Regards.

**Comment by jaypit02** [comment]
Answered the question.
